### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by Raiden9**
I just want to share an idea for a new logo. If you want something specific i can make it. ;)

Keep up the good work.

### CODE REVIEW

**Comment by evrignaud** [comment]
Hi VRad49,

I have discovered accidentally that you have created a new icon for Fim.
Unfortunately, your merge request have been submitted into your fork of Fim, not in the Fim repository.
That's why I haven't seen your contribution.

I would like to take in account what you did.
I would like to know what is the meaning of the drawing that you did. It's not a "classical" icon.
We see clearly the big 'i' of Fim I think. But for the other parts, I would like to know their meaning.
I have noticed that you kept some green, which is good.
Personally I find the black border too dark. I know that this dark border is interesting to raise the big 'i'.

Hoping to get your feeling soon,
/Etienne

**Comment by Raiden9** [comment]
Hi,
I don't know how to use correctly Github, i just wanted to show an idea for the fim logo.
I don't think this previous icon fit really well with fim so i made another one.
https://lut.im/fzarX0t3pJ/cphQTbwp5BZqCYfN.png

without the box
https://lut.im/ubBDg32EaZ/cNpVTefdoKs0WiJA.png

and just the box
https://lut.im/tOrl1s45wy/sLe5sQIYyjEDS3de.png

i can change colors, lights and shadows, just tell me. ;)

**Comment by evrignaud** [comment]
Awesome, thank you for this good job.
This icon is very good https://lut.im/fzarX0t3pJ/cphQTbwp5BZqCYfN.png
The transparency effects and the shadows are good.
Perhaps we could add shadows between:
- the F and the cube
- the M and the cube?

Regarding the colors, I have tried to add more yellow inside and I thinks it looks brighter like this.
https://lut.im/tqLSCpOvqM/EEKutNUDFcD2mVNZ.png
My image is just a quick and dirty test. I have just colorize the whole image.

**Comment by evrignaud** [comment]
In order to submit successfully a pool request perhaps you should take a look to this video that might help https://www.youtube.com/watch?v=G1I3HF4YWEw

**Comment by evrignaud** [comment]
What do you think of my returns from 6 days ago?

**Comment by evrignaud** [comment]
Could you provide me at least the .xcf file of the new Icon?
I'll manage to do the commit in the Fim master.

**Comment by Raiden9** [comment]
Sorry for my lack of answers but my pc has some problems.

---

Désolé de mon absence de réponse mon PC à eu quelques problèmes, peut-on se contacter par mail plutôt que via Github?

**Comment by evrignaud** [comment]
Yes we can contact by mail. My address is evrignaud at gmail dot com
In french if you prefer.

**Pull request merged**
